version: 2.1
jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run: java --version
      - run:
          name: Setup env
          command: |
            echo "API_KEY=$SENDGRID_API_KEY" >> app/src/test/resources/.env
            echo "TOS" >> app/src/test/resources/.env
            echo "FROM" >> app/src/test/resources/.env
      - run:
          name: Unit test
          command: mvn test

workflows:
  version: 2
  normal_deploy_workflow:
    jobs:
      - test
  monthly_workflow:
    triggers:
      - schedule:
          cron: "0 0 2 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test